# Generated by Django 5.2.7 on 2026-02-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
